# Generated by Django 6.1.1 on 2026-09-11 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='Masalan: 8600 1234 5678 9012', max_length=19, verbose_name='Karta raqami')),
                ('card_holder', models.CharField(blank=True, max_length=100, verbose_name='Karta egasi')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank nomi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "To'lov kartasi",
                'verbose_name_plural': "To'lov kartasi",
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/%Y/%m/', verbose_name='Chek rasmi')),
                ('status', models.CharField(choices=[('pending', 'Tekshirilmoqda'), ('approved', 'Qabul qilindi'), ('rejected', 'Bekor qilindi')], default='pending', max_length=10, verbose_name='Holati')),
                ('reject_reason', models.TextField(blank=True, verbose_name='Bekor qilish sababi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqti')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqti")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "To'lov cheki",
                'verbose_name_plural': "To'lov cheklari",
                'ordering': ['-created_at'],
            },
        ),
    ]
