"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6wk16-rqryxy8mttj38mwlg&z!bwjxag2y40bf$)+54cy!t365'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.100.121']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators
# Foydalanuvchi so'roviga ko'ra: parolga hech qanday cheklov yo'q (oddiy parollar ham ruxsat etiladi)
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (foydalanuvchi yuklagan rasmlar - chek va h.k.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Telegram bot orqali to'lov bildirishnomalari
# Foydalanuvchi chek yuklaganda (to'lov qilganda) shu botga xabar yuboriladi.
# TELEGRAM_CHAT_ID ni olish uchun:
#   1) Telegramda @tasdiqpay_bot ga /start yuboring (yoki botga istalgan xabar yozing)
#   2) Brauzerda oching: https://api.telegram.org/bot<TOKEN>/getUpdates
#   3) Javobdagi "chat":{"id": ...} qiymatini shu yerga qo'ying.
TELEGRAM_BOT_TOKEN = '8642924517:AAFuvZuxePYYSFrgFlbQf7XJCExkTyFYpQs'
TELEGRAM_CHAT_ID = '8380574008'  # <-- bu yerga admin/guruh chat_id sini kiriting

# Login/logout marshrutlari
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# Foydalanuvchi ISM orqali kiradi (email/username o'rniga)
AUTHENTICATION_BACKENDS = [
    'payments.backends.FirstNameBackend',
    'django.contrib.auth.backends.ModelBackend',  # admin panel uchun zaxira
]


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
