```python
"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

from pathlib import Path
import os


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY
# ============================================================

# Render Environment Variables orqali beriladi.
# Agar topilmasa, development uchun vaqtinchalik qiymat ishlatiladi.
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-change-this-secret-key"
)

DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

# Render uchun
ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "*"
).split(",")


# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "payments",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    # WhiteNoise CSS/JS/static fayllarni production'da serve qiladi
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URL / WSGI
# ============================================================

ROOT_URLCONF = "core.urls"

WSGI_APPLICATION = "core.wsgi.application"


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# DATABASE
# ============================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ============================================================
# PASSWORD VALIDATION
# ============================================================

# Foydalanuvchi so'roviga ko'ra parolga cheklov yo'q.
AUTH_PASSWORD_VALIDATORS = []


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = "uz"

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

# Muhim:
# Oxirida / bo'lishi kerak.
STATIC_URL = "/static/"

# Render collectstatic shu papkaga yig'adi.
STATIC_ROOT = BASE_DIR / "staticfiles"


# WhiteNoise orqali compressed static fayllar
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },

    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# ============================================================
# MEDIA FILES
# ============================================================

# Foydalanuvchi yuklagan rasmlar / cheklar
MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"


# ============================================================
# TELEGRAM BOT
# ============================================================

# Tokenlarni Render -> Environment Variables ichidan oladi.
#
# Render'da:
#
# TELEGRAM_BOT_TOKEN = yangi_bot_token
# TELEGRAM_CHAT_ID = 8380574008
#

TELEGRAM_BOT_TOKEN = os.environ.get(
    "TELEGRAM_BOT_TOKEN",
    ""
)

TELEGRAM_CHAT_ID = os.environ.get(
    "TELEGRAM_CHAT_ID",
    ""
)


# ============================================================
# LOGIN / LOGOUT
# ============================================================

LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "home"

LOGOUT_REDIRECT_URL = "login"


# ============================================================
# AUTHENTICATION
# ============================================================

# Foydalanuvchi ism orqali login qiladi.
AUTHENTICATION_BACKENDS = [
    "payments.backends.FirstNameBackend",

    # Django admin uchun
    "django.contrib.auth.backends.ModelBackend",
]


# ============================================================
# EMAIL
# ============================================================

# Hozircha email yuborish o'rniga console backend.
# Development uchun qulay.
#
# Keyinchalik haqiqiy email ishlatmoqchi bo'lsangiz,
# EMAIL_BACKEND / EMAIL_HOST va boshqa sozlamalarni qo'shamiz.

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"